openapi: 3.0.1
info:
  title: Test
  description: test
  version: "1.0"
paths:
  /test:
    get:
      parameters:
        - name: test
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: boolean
