openapi: 3.0.0
info:
  version: 1.0.0
  title: Test array response
paths:
  /test1:
    get:
      responses:
        '200':

          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Object'
components:
  schemas:
    Object:
      type: object
      properties:
        count:
          type: integer
