openapi: '3.0.3'
info:
  title: Simple example spec
  version: '1.0'
paths:
  /test1:
    get:
      parameters:
        - name: a
          in: query
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test1'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: string
        423:
          description: No response
      deprecated: true
components:
  schemas:
    Test1:
      type: object
      properties:
        name:
          type: string
        size:
          type: integer
